# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 10:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20170726_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, blank=True, editable=False, max_length=100, populate_from=models.CharField(max_length=100), unique_with=['name']),
        ),
    ]
