# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 11:20
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, blank=True, editable=False, max_length=100, populate_from='name', unique_with=['name']),
        ),
    ]
