# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20170816_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bn_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name in Bangla'),
        ),
    ]
