# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_types', '0003_auto_20170816_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='bn_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
