# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=10),
        ),
    ]
