# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 06:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170717_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['publish_date__month', 'publish_date__day']),
        ),
    ]
