# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('articles', '0005_auto_20170726_1526'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('slug', 'publish_date', 'site')]),
        ),
    ]
