# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170726_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vedio_youtube_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
