# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 09:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_vedio_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_attachments', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_gfx',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_detail_gfxs', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='gfx',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_gfxs', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='vedio',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_vedios', to='filer.File'),
        ),
    ]
