# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('articles', '0012_auto_20170812_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetailGfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleGfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='detail_gfx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='gfx',
        ),
        migrations.AddField(
            model_name='articlegfx',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfxs', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlegfx',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
        migrations.AddField(
            model_name='articledetailgfx',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_gfxs', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articledetailgfx',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
