# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 15:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('articles', '0013_auto_20170816_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='vedio_youtube_url',
            new_name='video_youtube_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='vedio',
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_videos', to='filer.File'),
        ),
    ]
