# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('articles', '0016_article_in_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAtachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('youtube_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='articledetailgfx',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articledetailgfx',
            name='image',
        ),
        migrations.RemoveField(
            model_name='articlegfx',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlegfx',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_youtube_url',
        ),
        migrations.DeleteModel(
            name='ArticleDetailGfx',
        ),
        migrations.DeleteModel(
            name='ArticleGfx',
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
        migrations.AddField(
            model_name='articlephoto',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlephoto',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
        migrations.AddField(
            model_name='articleatachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articleatachment',
            name='attachment',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
