# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20170820_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='in_focus_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Order in Focus'),
        ),
    ]
