# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20170930_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
