# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20170930_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
