# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 14:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import albd.articles.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20171002_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=1000, populate_from=albd.articles.models.unique_slug_generator),
        ),
    ]
