# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20171002_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleatachment',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlephoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='fb_video',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
