# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-27 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20181124_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('liberator', 'liberator'), ('celebration', 'celebration'), ('history', 'history'), ('video', 'video'), ('opinion', 'opinion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='articleatachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_list', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_list', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='articlevideo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_list', to='articles.Article'),
        ),
    ]
