# Generated by Django 3.1.7 on 2021-03-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
        ('filer', '0012_file_mime_type'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('articles', '0030_auto_20200227_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.position'),
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='articlevideo',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file'),
        ),
        migrations.DeleteModel(
            name='ArticleAtachment',
        ),
        migrations.AddField(
            model_name='articleattachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_list', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articleattachment',
            name='attachment',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file'),
        ),
    ]
