# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 04:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, blank=True, editable=False, max_length=100, populate_from='title', unique_with=['title'])),
                ('link', models.URLField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'verbose_name_plural': 'Top Banners',
                'ordering': ['-published'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='topbanner',
            unique_together=set([('slug', 'published')]),
        ),
    ]
