# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbanner',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
