# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_banners', '0003_auto_20171110_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='type',
            field=models.CharField(choices=[('S', 'Static'), ('M', 'Main')], default='M', max_length=2),
        ),
    ]
