# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_banners', '0005_topbanner_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='show_instruction',
            field=models.BooleanField(default=True),
        ),
    ]
