# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=960)),
                ('write_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
