# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0010_auto_20180130_1027'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='joinus.Constituency'),
        ),
        migrations.AddField(
            model_name='message',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='joinus.District'),
        ),
        migrations.AddField(
            model_name='message',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='joinus.Division'),
        ),
        migrations.AddField(
            model_name='message',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Mobile'),
        ),
    ]
