# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0010_auto_20180130_1027'),
        ('messaging', '0002_auto_20180226_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=13, null=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=100)),
                ('text', tinymce.models.HTMLField()),
                ('write_time', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='joinus.Constituency')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='joinus.District')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='joinus.Division')),
            ],
        ),
    ]
