# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20180407_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='include_joinus',
            field=models.BooleanField(default=True, verbose_name='Include Joinus'),
        ),
        migrations.AddField(
            model_name='message',
            name='include_joinus',
            field=models.BooleanField(default=True, verbose_name='Include Joinus'),
        ),
    ]
