# Generated by Django 3.1.7 on 2021-05-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0011_auto_20210317_0137'),
        ('messaging', '0006_auto_20180414_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email', to='joinus.constituency'),
        ),
        migrations.AlterField(
            model_name='email',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email', to='joinus.district'),
        ),
        migrations.AlterField(
            model_name='email',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email', to='joinus.division'),
        ),
        migrations.AlterField(
            model_name='message',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='joinus.constituency'),
        ),
        migrations.AlterField(
            model_name='message',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='joinus.district'),
        ),
        migrations.AlterField(
            model_name='message',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='joinus.division'),
        ),
    ]
