# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 07:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
