# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('pages', '0002_auto_20170818_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('slug', 'published_date', 'site')]),
        ),
    ]
