# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 17:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170819_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
