# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170917_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=10),
            preserve_default=False,
        ),
    ]
