# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('video', 'General Video'), ('info', 'InfoGraphic'), ('history', 'History')], max_length=20)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('publish_date', models.DateTimeField()),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('local', 'Local')], max_length=10)),
                ('embedded_link', models.URLField(blank=True, verbose_name='Embedded Link')),
                ('order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gallery.Gallery')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='filer.Image')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
            },
        ),
    ]
