# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('video', 'General Video'), ('info', 'InfoGraphic'), ('history', 'History'), ('live', 'Live')], max_length=20),
        ),
    ]
