# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-03-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20181124_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
