# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('carousel_caption', models.CharField(blank=True, max_length=250)),
                ('order', models.ImageField(blank=True, default=0, upload_to='')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('cover_page', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
        ),
    ]
