# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 11:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import albd.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('on_site', albd.publications.models.PublicationManager()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, blank=True, editable=False, max_length=100, populate_from='title', unique_with=['title']),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('slug', 'published', 'site')]),
        ),
    ]
