# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20170819_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
