# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:55
from __future__ import unicode_literals

from django.db import migrations
import albd.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_lang'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('objects', albd.publications.models.PublicationManager()),
            ],
        ),
    ]
