# Generated by Django 3.1.7 on 2021-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20171129_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
