# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinus',
            options={'verbose_name': 'Join Us', 'verbose_name_plural': 'Join Us'},
        ),
    ]
