# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0002_auto_20171110_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='district',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='district',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='joinus.Division'),
            preserve_default=False,
        ),
    ]
