# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0004_joinus_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='joinus.Constituency'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='joinus.District'),
        ),
    ]
