# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0005_auto_20171125_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='district',
            name='parent',
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='joinus.District'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='joinus.Division'),
        ),
    ]
