# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0006_auto_20171125_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituency',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 28, 10, 13, 28, 281559, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='division',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
