# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0007_auto_20171128_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name': 'Constituency', 'verbose_name_plural': 'Constituencies'},
        ),
    ]
