# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0008_auto_20171128_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
